# Generated by Django 5.1.3 on 2024-11-13 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='admin_dashboard.labour')),
            ],
        ),
    ]
